server:
  port: 8082
  error:
    include-stacktrace: always

spring:
  application:
    name: authorization-server

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: sso
        format_sql: true

  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

e-mail:
  host: smtp.mail.ru
  port: 465
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  protocol: smtp
  properties:
    mail.smtp.auth: true
    mail.smtp.ssl.enable: true

JWT_SECRET_KEY: ${JWT_SECRET_KEY}
EMAIL_TEMPLATE: ${EMAIL_TEMPLATE_PATH}

otp-store:
  cookie-name: oous-sso-temporary-session
  cookie-domain: localhost
  cookie-max-age: 180